<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE fiwalk
[
<!ELEMENT alloc ANY >
<!ELEMENT arch ANY >
<!ELEMENT atime ANY >
<!ELEMENT block_count ANY >
<!ELEMENT block_size ANY >
<!ELEMENT build_environment ANY >
<!ELEMENT byte_runs ANY >
<!ELEMENT command_line ANY >
<!ELEMENT compilation_date ANY >
<!ELEMENT compiler ANY >
<!ELEMENT compressed ANY >
<!ELEMENT creator ANY >
<!ELEMENT crtime ANY >
<!ELEMENT ctime ANY >
<!ELEMENT dc:type ANY >
<!ELEMENT dfxml ANY >
<!ELEMENT execution_environment ANY >
<!ELEMENT faults ANY >
<!ELEMENT filename ANY >
<!ELEMENT fileobject ANY >
<!ELEMENT filesize ANY >
<!ELEMENT first_block ANY >
<!ELEMENT ftype ANY >
<!ELEMENT ftype_str ANY >
<!ELEMENT gid ANY >
<!ELEMENT hashdigest ANY >
<!ELEMENT host ANY >
<!ELEMENT id ANY >
<!ELEMENT image_filename ANY >
<!ELEMENT inode ANY >
<!ELEMENT inputs ANY >
<!ELEMENT last_block ANY >
<!ELEMENT library ANY >
<!ELEMENT maxrss ANY >
<!ELEMENT meta_type ANY >
<!ELEMENT metadata ANY >
<!ELEMENT mode ANY >
<!ELEMENT mtime ANY >
<!ELEMENT name_type ANY >
<!ELEMENT nlink ANY >
<!ELEMENT os_release ANY >
<!ELEMENT os_sysname ANY >
<!ELEMENT os_version ANY >
<!ELEMENT outputs ANY >
<!ELEMENT partition ANY >
<!ELEMENT partition_offset ANY >
<!ELEMENT program ANY >
<!ELEMENT reclaims ANY >
<!ELEMENT runstats ANY >
<!ELEMENT seq ANY >
<!ELEMENT source ANY >
<!ELEMENT start_time ANY >
<!ELEMENT start_timet ANY >
<!ELEMENT stop_time ANY >
<!ELEMENT swaps ANY >
<!ELEMENT system_seconds ANY >
<!ELEMENT uid ANY >
<!ELEMENT used ANY >
<!ELEMENT user_seconds ANY >
<!ELEMENT username ANY >
<!ELEMENT version ANY >
<!ELEMENT volume ANY >
<!ATTLIST volume startsector CDATA #IMPLIED>
<!ATTLIST run start CDATA #IMPLIED>
<!ATTLIST run len CDATA #IMPLIED>
]>
<dfxml xmloutputversion='0.3'>
  <metadata 
  xmlns='http://afflib.org/fiwalk/' 
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
  xmlns:dc='http://purl.org/dc/elements/1.1/'>
    <dc:type>Disk Image</dc:type>
  </metadata>
  <creator>
    <program>fiwalk</program>
    <version>0.6.6</version>
    <build_environment>
      <compiler>GCC 4.4</compiler>
      <compilation_date>Mar 15 2011 16:07:20</compilation_date>
      <library name="tsk" version="3.2.0"></library>
      <library name="afflib" version="3.6.4"></library>
      <library name="libewf" version="20100119"></library>
    </build_environment>
    <execution_environment>
      <os_sysname>Linux</os_sysname>
      <os_release>2.6.35-22-generic</os_release>
      <os_version>#33-Ubuntu SMP Sun Sep 19 20:34:50 UTC 2010</os_version>
      <host>station12</host>
      <arch>i686</arch>
      <command_line>fiwalk -d -n ntuser -X /home/emschwe/jean-ntuser-carve.xml nps-2008-jean.E01 nps-2008-jean.E02</command_line>
      <uid>1002</uid>
      <username>emschwe</username>
      <start_time>Tue Mar 15 16:51:27 2011</start_time>
      <start_timet>1300222287</start_timet>
    </execution_environment>
  </creator>
  <source>
    <image_filename>nps-2008-jean.E01</image_filename>
  </source>
<!-- fs start: 32256 -->
  <volume offset='32256'>
    <partition_offset>32256</partition_offset>
    <block_size>4096</block_size>
    <ftype>1</ftype>
    <ftype_str>ntfs</ftype_str>
    <block_count>2618587</block_count>
    <first_block>0</first_block>
    <last_block>2618586</last_block>
    <fileobject>
      <filename>Documents and Settings/Administrator/NTUSER.DAT</filename>
      <partition>1</partition>
      <id>1</id>
      <name_type>r</name_type>
      <filesize>786432</filesize>
      <alloc>1</alloc>
      <used>1</used>
      <inode>10226</inode>
      <meta_type>1</meta_type>
      <mode>365</mode>
      <nlink>1</nlink>
      <uid>0</uid>
      <gid>0</gid>
      <mtime>1216603861</mtime>
      <ctime>1216603850</ctime>
      <atime>1216603861</atime>
      <crtime>1210714210</crtime>
      <seq>1</seq>
      <byte_runs>
       <run file_offset='0' fs_offset='0' img_offset='3003527168' len='1'/>
       <run file_offset='643072' fill='0' len='0'/>
      </byte_runs>
    </fileobject>
  </volume>
<!-- end of volume -->
<!-- clock: 22 -->
  <runstats>
    <user_seconds>11</user_seconds>
    <system_seconds>0</system_seconds>
    <maxrss>11136</maxrss>
    <reclaims>3771</reclaims>
    <faults>1</faults>
    <swaps>0</swaps>
    <inputs>482080</inputs>
    <outputs>1776</outputs>
    <stop_time>Tue Mar 15 16:51:49 2011</stop_time>
  </runstats>
</dfxml>
